name: zeczec manual crawler

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Manually run the script"
        required: false
jobs:
  crawl:
    runs-on: 'ubuntu-latest'
    container:
      image: plantpractice01/zec-plant:latest
      credentials:
        username: plantpractice01
        password: ${{secrets.DOCKER_HUB_TOKEN}}
    steps:
      - uses: actions/checkout@v2
